// src/actions/actionTypes.js

export const LOG_IN_REQUEST = 'LOG_IN_REQUEST'
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS' 
export const LOG_IN_ERROR = 'LOG_IN_ERROR'

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_ERROR  = 'SIGN_UP_ERROR'

export const DRONE_CREATE_REQUEST = 'DRONE_CREATE_REQUEST'
export const DRONE_UPDATE_REQUEST = 'DRONE_UPDATE_REQUEST'
export const FETCH_ALL_DRONES = 'FETCH_ALL_DRONES'
export const FETCH_ALL_DRONES_SUCCESS = 'FETCH_ALL_DRONES_SUCCESS'
export const FETCH_DRONE_POSITION = 'FETCH_DRONE_POSITION'

export const ADD_STEP = 'ADD_STEP'
export const SET_CURSOR_POSITION  = 'SET_CURSOR_POSITION'
export const REMOVE_STEP = 'REMOVE_STEP'
export const UPDATE_POSITION = 'UPDATE_POSITION'


